#pragma once
void TestDefaultConstructor();
void TestParametricConstructor();
void TestSquareBracketOperator();
void TestIndirectionOperator();
void TestCopyConstructor();
void TestAssignmentOperator();
void TestMoveConstructor();
void TestMoveAssignmentOperator();
void TestIndexOutOfBoundException();
